image: node

cache:
  paths:
    - node_modules/

stages:
  - build
  - test

build:
  stage: build
  script:
    - yarn install
    - yarn run compileSass
    - yarn run compileTs

test:
  stage: test
  script:
    - yarn install
    - yarn run test